In [2]:
# copy first n lines of "./dataset/Music_Review_train.json" and store it to "./dataset/Music_Review_train_temp.json"
with open("./dataset/Music_Review_test.json", "r") as f:
    lines = f.readlines()
    with open("./dataset/Music_Review_test_temp.json", "w") as f:
        for line in lines[:1000]:
            f.write(line)
with open("./dataset/Music_Review_train.json", "r") as f:
    lines = f.readlines()
    with open("./dataset/Music_Review_train_temp.json", "w") as f:
        for line in lines[:1000]:
            f.write(line)


In [7]:
import numpy as np
X=np.load('X_test_clean_tr_q1.npy',allow_pickle=True)
print(X.shape)
X=np.load('X_test_clean_q1.npy',allow_pickle=True)
print(X.shape)

(14000,)
(14000,)


In [8]:
X=np.load('X_train_clean_tr_q1.npy',allow_pickle=True)
print(X.shape)

(50000,)


In [9]:
X=[]

In [28]:

# import these modules
from nltk.stem import WordNetLemmatizer
 
lemmatizer = WordNetLemmatizer()
 
print("rocks :", lemmatizer.lemmatize("rocks"))
print("corpora :", lemmatizer.lemmatize("corpora"))
 
# a denotes adjective in "pos"
print("better :", lemmatizer.lemmatize("of"))

rocks : rock
corpora : corpus
better : of


In [25]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\91930\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [1]:
mydict={'a':1,'b':2,'c':3}
print(len(mydict))

3


In [3]:
import numpy as np
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

c = np.array([0,1,2])
t=c*m
print(t)
print(t*t.T)

[[ 0  2  6]
 [ 0  5 12]
 [ 0  8 18]]
[[  0   0   0]
 [  0  25  96]
 [  0  96 324]]


In [18]:
from PIL import Image
import numpy as np
from libsvm.svmutil import *

# load model
model = svm_load_model('model.txt')
print(model) 
# generate image from 1d array of 784 pixels
t=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,117,254,220,89,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,95,212,253,253,253,157,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,95,209,253,253,253,245,125,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40,96,206,253,254,253,253,198,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,44,182,240,253,253,253,254,253,198,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,60,60,168,253,253,254,200,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,70,247,253,253,245,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,207,253,253,207,92,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,79,219,253,253,253,138,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,105,250,253,253,253,34,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,95,254,254,254,254,94,0,0,0,0,0,3,13,13,13,8,0,0,0,0,0,0,0,0,0,0,0,0,107,253,253,253,204,15,0,0,0,0,21,166,253,253,253,212,25,0,0,0,0,0,0,0,0,0,0,33,217,253,253,132,64,0,0,18,43,157,171,253,253,253,253,253,160,2,0,0,0,0,0,0,0,0,3,166,253,253,242,49,17,49,158,210,254,253,253,253,253,253,253,253,253,11,0,0,0,0,0,0,0,0,10,227,253,253,207,15,172,253,253,253,254,247,201,253,210,210,253,253,175,4,0,0,0,0,0,0,0,0,10,228,253,253,224,87,242,253,253,184,60,54,9,60,35,182,253,253,52,0,0,0,0,0,0,0,0,0,13,253,253,253,253,231,253,253,253,93,86,86,86,109,217,253,253,134,5,0,0,0,0,0,0,0,0,0,2,115,253,253,253,253,253,253,253,253,254,253,253,253,253,253,134,5,0,0,0,0,0,0,0,0,0,0,0,3,166,253,253,253,253,253,253,253,254,253,253,253,175,52,5,0,0,0,0,0,0,0,0,0,0,0,0,0,7,35,132,225,253,253,253,195,132,132,132,110,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]).reshape(28,28)
img = Image.fromarray(t)
# save image
print(model.)
img.convert('RGB').save('test.jpeg')
img.show()

In [42]:
# read 0th column from csv file
import pandas as pd
df = pd.read_csv('./multi-libsvm-miss/missclassified_test.csv', usecols=[0],header=None)
data=pd.read_csv('./dataset/test.csv',header=None)
# select all but last column
data=data.iloc[:,:-1]
data=np.array(data)
df=np.array(df)
for i in range(len(df)):
    print(df[i])
    img=Image.fromarray(np.array(data[df[i][0]]).reshape(28,28).astype(np.uint8))
    img.convert('RGB').save("./multi-libsvm-miss/miss_test_"+str(i)+".jpeg")


[2087]
[2675]
[3739]
[4377]
[4441]
[6240]
[6383]
[7572]
[9187]
[9323]
[9473]
[10820]
[11339]
[13098]
[13483]
[14533]


In [28]:
print(df[0][0])

2675


In [7]:
import numpy as np
final_pred_train=np.array([{10:1,20:1},{10:2,20:2},{10:3,20:3},{10:4,20:4},{10:5,20:5},{10:6,20:6},{10:7,20:7},{10:8,20:8}])
Y_pred_train=np.array([1,1,1,1,-1,-1,-1,-1])
temp=final_pred_train
print(final_pred_train[np.where(Y_pred_train==1)])
print(final_pred_train[np.where(Y_pred_train==1)][0])
final_pred_train[np.where(Y_pred_train==1)][10]+=1
final_pred_train[np.where(Y_pred_train==-1)][20]+=1
print(final_pred_train)

[{10: 1, 20: 1} {10: 2, 20: 2} {10: 3, 20: 3} {10: 4, 20: 4}]
{10: 1, 20: 1}


IndexError: index 10 is out of bounds for axis 0 with size 4

In [1]:
import numpy as np
alpha=np.array([1,2])
supp=np.array([[1,2,3,4],[1,2,3,5]])

supp_y=np.array([1,1])
X=np.array([[10,1,1,1],[1,1,1,1],[1,1,1,1]])
print(X[0]-supp)
a=np.dot(alpha,np.diag(supp_y))
print(a)
b=np.exp(-0.05*np.linalg.norm(X[0]-supp,axis=1)**2)
print(b)
c=np.diag(b)
c=np.dot(a,c)
print(c)

[[ 9 -1 -2 -3]
 [ 9 -1 -2 -4]]
[1 2]
[0.0086517  0.00609675]
[0.0086517  0.01219349]


In [12]:
squarer = lambda x: np.sum(np.dot(np.dot(alpha,np.diag(supp_y)),np.diag(np.exp(-0.05*np.linalg.norm(x-supp,axis=1)**2))))
print(X)
pred=np.apply_along_axis(squarer,1,X)
print(pred)

[[10  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1  1]]
[0.02084519 1.1964608  1.1964608 ]


In [20]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,5])
print(a*b)

[ 1  4  9 20]
